### ISSUE TITLE
How to unmark

### ISSUE THREAD

**Issue by c02y** [magnars/multiple-cursors.el#170]
For example, I want to insert spaces at the beginning of Line 2~6, use `C->` to go through the beginning of every line starting from Line 2, but the I accidently type one more time of  `C->` which also mark the beginning of Line 7, I want to unmark Line 7 to go back to the state that the point was at the beginning of Line 6, how can I do that?

I thought I could just use `UP` or `C-p` to unmark Line 7, but it move the marks to mark Line 1~6, this is not I want. So how can I undo the last mark???

Commands `mc/unmark-next/previous-like-this` don't work at all, even if the commands work, I have to type the command in `M-x` to unmark the last mark, binding them to a command such as `UP/Down` or C-n/p` in the process of multiple-cursors to unmark is a great idea.

**Comment by dovej** [comment]
Since mc/mark-next-like-this, with no region, adds a cursor to the next line at the same position, I expected mc/unmark-next-like-this to do the opposite (i.e. remove the bottom most cursor). Since it sounds like the behavior for mc/mark-next-like-this is a feature, I think it makes sense to make the unmark behavior consistent with that. Ditto for the "previous" functions too.

**Comment by magnars** [comment]
Fixed via #193
