### ISSUE TITLE
mc/mark-more-like-this-extended ignores left/right

### ISSUE THREAD

**Issue by pronobis** [magnars/multiple-cursors.el#194]
It seems that up/down keys work as expected, but left/right do not remove/skip for me. Could you verify it that's a problem in MC or maybe I have some weird conflict?

**Comment by magnars** [comment]
It works for me. Just checked. What are the keys bound to when you're in the middle of marking?

**Comment by pronobis** [comment]
Thanks, would would be the best way to check that? Anything I tried interrupts the extended mode.

**Comment by magnars** [comment]
Ah, I guess you're right - it's implemented as just reading chars off the input stream. Maybe you could call `M-x edebug-defun` on the command in question and see what happens?

**Comment by pronobis** [comment]
OK, so it seems that `mc/mmlte--right` is invoked. I followed it down to 
`mc/mark-next-like-this` in which `(mc/mark-lines arg 'forwards)` is run and does not do anything.

**Comment by magnars** [comment]
Hmm, that is also weird. Does `mc/mark-next-like-this` also not do anything when used on its own?

**Comment by meta-coder** [comment]
@pronobis Are you using ```mc/mark-more-like-this-extended``` command without any region activated?

**Comment by vspinu** [comment]
I can confirm this. 

To be more specific, `mc/mark-more-like-this-extended` is not ignoring <left> when there is a selection. It ignores only when you start it with no selection. 

That's because [mc/mark-next-like-this](https://github.com/magnars/multiple-cursors.el/blob/master/mc-mark-more.el#L158-L165) checks for region and as region is not active negative `arg` is passed to `mc/mark-lines` which  ultimately does nothing.

**Comment by vspinu** [comment]
Seems that PR #193 fixes that. Any chance it can be merged soon?

**Comment by magnars** [comment]
#193 is now merged. Closing this. Reopen if the issue reemerges.
