### ISSUE TITLE
A recent commit broke the mc/mark-next-like-this command

### ISSUE THREAD

**Issue by kaushalmodi** [magnars/multiple-cursors.el#201]
After this commit ( https://github.com/magnars/multiple-cursors.el/commit/2d6ffce4c94cdbec1ea8ec086ea346423bafcdf1 ), I cannot use `mc/mark-next-like-this` (bound to `C->`) for more than two lines. 

Without setting any mark, I used to press `C->` two times to create 3 multiple cursors in the same column on 3 consecutive lines.

After the above commit, pressing `C->` the first time creates the second multiple cursor on the second line. Pressing `C->` again creates a multiple cursor at the same spot on the second line instead of creating one on the third line.

I can fix this issue by evaluating a commit older to that ( https://raw.githubusercontent.com/magnars/multiple-cursors.el/72b4bf3911cc18e87a80b2152a6f707d12f2b531/mc-mark-more.el ).

**Comment by magnars** [comment]
Doh, thanks for the report. I'll revert the broken commit.

**Comment by sjrmanning** [comment]
For what it's worth I'm having the same issue, but seemingly only with `mc/mark-previous-like-this`, however I can only assume it's related.

**Comment by dovej** [comment]
Huh...this is very weird, because I tested that. Can someone help me debug this? Because now that I'm trying to repro this I'm finding very strange behavior.

If I start a fresh emacs (quit emacs, restart), switch to the scratch buffer, type a few lines, then try mark-next-like-this (or previous) I get "Wrong type argument: number-or-marker-p, nil". However, if I set then deactivate the mark (C-SPC C-SPC) *everything begins working exactly as it should*.

There is a different set of initial behaviors on a fresh emacs that will cause the issue kaushalmodi is reporting and another that will cause the complementary issue that sjrmanning is reporting, however, I haven't figured out exactly what they are yet and I'm not sure how much time I'll have over the next few weeks to look into this.

Anyone want to help?

**Comment by magnars** [comment]
>  I get "Wrong type argument: number-or-marker-p, nil". However, if I set then deactivate the mark (C-SPC C-SPC) everything begins working exactly as it should.

This, at least, is explainable. Calling `(mark)` on a new Emacs, gives `nil`. After you set mark the first time, even if the region is activated, the mark is still there, giving a position instead.

If you are able to reconstruct the issues with detailed steps, I can try to find the time to investigate.

**Comment by dovej** [comment]
Alright, I actually found the source of all three bugs, but I need some advice on how to fix it.

The issues arise because I'm using mc/furthest-cursor-after-point in mc/mark-lines. Specifically, I expected this function to just find the furthest cursor after the point, but it seems it actually has some behavior that depends on the mark: " (let ((end (max (mark) (point))) furthest)".

If you never had a mark in the current emacs session, this function errors with the error mentioned earlier. Perhaps this in and of itself is a bug? If you activate and then immediately deactivate a mark, then leaving the point there begin calling (un)mark-next(previous)-like this, everything works fine. However, if you instead activate/deactivate a mark and then move the point to a different line, you get the issues mentioned by the other users in this thread. Whether the mark is below or above the point determines which issue you'll see of the two. This very clearly all boils down to the line of mc/furthest-cursor-after-point that I mentioned above.

So, the questions are: 1) does mc/furthest-cursor-after-point need to be changed in any way? and 2) should I be using a different function to do the job I was trying to do in mc/mark-lines?

**Comment by magnars** [comment]
Good detective work!

It sounds to me like `mc/furthest-cursor-after-point` is broken. Does this fix it?

Change

```cl
 (let ((end (max (mark) (point))) furthest)
```

to

```cl
 (let ((end (max (or (mark) 1) (point))) furthest)
```

**Comment by dovej** [comment]
It takes away the error on a fresh emacs for mark-next-like-this, but doesn't fix it for mark-previous-like-this. It turns out there is also a line "(let ((beg (min (mark) (point))) furthest)" that needs to be modified in the complementary function mc/further-cursor-before-point.

Even though making these changes gets rid of the type argument errors, it doesn't fix the behavior kaushalmodi and sjrmanning discovered, mc/furthest-cursor-after(before)-point still returns the mark itself (even if it is deactivated) in some conditions, instead of the true furthest cursor. It's not clear to me why the mark should be involved in these functions at all.

Replacing instead with (let ((end (point)) furthest) and (let ((beg (point)) furthest) respectively fixes the problem, but I don't know what other behavior that might break in other functions...Any idea why these functions involve the mark at all, particularly when it is deactivated?

**Comment by kaushalmodi** [comment]
@dovej I used to get issues with `mc/mark-next-like-this` or `mc/mark-previous-like-this` (randomly). I guess it depended on whether the `mark` was greater than `point` or vice versa. But that issue is gone for me since commit https://github.com/magnars/multiple-cursors.el/commit/2588ccef6939b77896105f23642483c30c4a4e06

**Comment by dovej** [comment]
Yea, that's because that commit revoked my commit which had changed the behavior of these functions in order to fix #166 and #170. I'm trying to tease out how to reintroduce my fix without causing the issues you experienced. As it stands, 2588cce has reintroduced the issues from #166 and #170.

**Comment by magnars** [comment]
I can bring light to why `(mark)` is considered in these functions: it's because we don't want overlapping regions. So this prevents you from searching for a new position for a next cursor inside an active region. It should certainly be used only when there is an active region, tho, so that is a bug.

Does adding a check for active region solve the problem?

**Comment by dovej** [comment]
Okay, makes sense. I was thinking the same thing. Sure enough, the original code for these functions with the extra check for active-mark appears to fix everything. How should I push this, commit on top of my previous commit then issue a new pull request?

**Comment by magnars** [comment]
That would be great, thanks.

**Comment by jtamagnan** [comment]
It seems like this issue was fixed
