### ISSUE TITLE
Error in post-command-hook (mc/execute-this-command-for-all-cursors): (quit)

### ISSUE THREAD

**Issue by azagoruyko** [magnars/multiple-cursors.el#259]
`Error in post-command-hook (mc/execute-this-command-for-all-cursors`
Bug, when I'm trying to quit from multiple-cursors (C-g).

This bug is recent, so I havn't got it before.

**Comment by azagoruyko** [comment]
This error only occurs when C-g is binded to lambda. I've binded C-g to lambda with  `unhighlight-regexp` and `keyboard-quit`. When I turned back all works fine.

**Comment by jtamagnan** [comment]
Could you give me a formula to reproduce this exactly? Thank you

**Comment by nispio** [comment]
You will need to make a special version of your lambda to bind to `C-g` in `mc/keymap` that calls `mc/keyboard-quit` instead of regular `keyboard-quit`.  The problem is that `keyboard-quit`  works by signalling a quit, which is roughly equivalent to throwing an exception.  Therefore, the post-command-hook is aborted before completing it's work.

**Comment by azagoruyko** [comment]
Thanks a lot!
