### ISSUE TITLE
Option to allow electric for all cursors

### ISSUE THREAD

**Issue by dmalyuta** [magnars/multiple-cursors.el#287]
When I am editing a C++ file and have multiple cursors, typing something like `<` brings up a prompt `Do c-electric-lt-gt for all cursors? (y or n)`. I always answer `y`, so I'd like to know if it's possible to have an option to bypass this question (i.e. just assume yes).

**Comment by nispio** [comment]
To clarify, are you saying that you keep getting prompted for the _same_ command each time you use it?  Or you just want multiple-cursors to know about all of the commands in the various "electric" modes and treat them special?

**Comment by dmalyuta** [comment]
I get prompted to answer `(y or n)` when entering a symbol which is electric (like `(`, `[` and `<`) and also for instance when backward-deleting a word. However, once I answer `y`, the next time I perform this operation there is no prompr (it "remembers" my last choice). However, this doesn't last - I guess there is some timeout/condition because eventually I get prompted again. I would simply like an option to not get prompted at all and assume the `y` answer, so that my workf,low is not disrupted by a prompt which I anyway always answer `y` to.

**Comment by nispio** [comment]
The mechanism by which multiple-cursors "remembers" your choices is through a file called `.mc-lists.el` which is usually saved at `~/.emacs.d/mc-lists.el`.  If your preferences aren't getting saved, it is most likely because of a problem with reading/writing that file.

That said, if you wanted to add a snippet to your emacs init file that would ensure that you don't get prompted for those variables, you could always explicitly call them out.  Something like this should work:

```
(eval-after-load "multiple-cursors"
  '(progn
     (setq mc/cmds-to-run-for-all
	   (append
	    '(c-electric-star
	      c-electric-brace
	      c-electric-paren
	      c-electric-colon
	      c-electric-slash
	      c-electric-lt-gt
	      c-electric-pound
	      c-electric-delete
	      c-electric-backspace
	      c-electric-semi&comma
	      c-electric-delete-forward)
	    mc/cmds-to-run-for-all))))
```

**Comment by dmalyuta** [comment]
Most excellent! Thank you. In case any issue persists, I'll write back here.
