### ISSUE TITLE
Is mc broken as of 4 Feb 2018?

### ISSUE THREAD

**Issue by rebcabin** [magnars/multiple-cursors.el#322]
#### Description :octocat:
`mc/edit-lines` no longer works as expected.

#### Reproduction guide :beetle:

- Fresh pull of [spacemacs develop branch](https://github.com/syl20bnr/spacemacs/tree/develop) 

- Add the following packages to `~/.spacemacs`

```
dotspacemacs-additional-packages
 '(cedet               command-log-mode  edit-server
   epresent            function-args     figlet
   irony               lorem-ipsum       multiple-cursors
   rainbow-identifiers w3m               wgrep  )
```
- Start emacs

*Observed behaviour:* :eyes: :broken_heart:
`M-x mc/edit-lines` puts various cursor-looking blobs on the screen and does not
exit. After a few `C-g` presses, it goes away, but never functions properly.

*Expected behaviour:* :heart: :smile:
See https://github.com/magnars/multiple-cursors.el

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0e3a371)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-enable-clang-support t)
                 clojure common-lisp csv dash emacs-lisp fsharp git haskell helm html javascript markdown octave org python spell-checking sql syntax-checking yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by nispio** [comment]
There has not been a change to MC in months, so I feel confident in saying
that no, it is not broken as of today. A few notes about your bug report:

- You did not mention whether you have ever used MC before. If so, what
changed since last time?
- You didn't really describe how you were trying to use MC besides the name
of the command you tried to use.
- As with pretty much any emacs package, if you suspect a bug in MC, you
should try to reproduce the bug from `emacs -q`.  In other words, run
without any personal config besides the minimum required to run MC.  You
have given a list of packages and layers that may be causing conflicts, so
get rid of them and try again.

**Comment by rebcabin** [comment]
Confirmed it works outside of spacemacs. Still does not work inside spacemacs. Been using it for years inside spacemacs and never had an issue. Spacemacs is getting huge, though, and I'm not terribly surprised that it's starting to break down. Had lots of trouble with it lately. Back to DIY emacs I guess.

**Comment by nispio** [comment]
Were you able to try `multiple-cursors` in a minimal Spacemacs (i.e., no other packages or layers)?  If the latest Spacemacs has created some incompatibility with MC, it would definitely be worth investigating.  Even package incompatibilities would be good to know about if you can identify where the conflict is.  Good Luck!
